export const Url = 'http://localhost:5000';
export const HomePath = '/';
export const RecipesHome = '/recipes'
export const RecipePath = '/recipe'
export const UserData = '?user='
export const FilterQuery = '?filter='
export const LoginPath = '/login';
export const RegisterPath = '/register';
export const AddRecipePath = '/add_recipe';
export const AddIngredientPath = '/add_recipe/ingredient';
export const LikedRecipePath = '/liked_recipes';